### ISSUE TITLE
Create mongodb register/login system

### ISSUE THREAD

**Issue by bluquar** [dandelion-community/aid-app-monorepo#15]
https://github.com/guruhariharaun/Registration-and-Login-Form-in-Nodejs-and-MongoDB

**Comment by bluquar** [comment]
"passport"

**Comment by lowellbander** [comment]
http://www.passportjs.org/

**Comment by lowellbander** [comment]
searched "mongodb passport"
- https://medium.com/swlh/set-up-an-express-js-app-with-passport-js-and-mongodb-for-password-authentication-6ea05d95335c seemed promising but behind paywall
- https://www.ctl.io/developers/blog/post/build-user-authentication-with-node-js-express-passport-and-mongodb also promising but uses a stack we won't be using, like templated HTML with Handelbars, CenturyLink for hosting the MongoDB, etc.

**Comment by lowellbander** [comment]
> [Passport-Local Mongoose](https://www.npmjs.com/package/passport-local-mongoose) is a Mongoose plugin that simplifies building username and password login with Passport.

Found from https://dev.to/muhammadawaisshaikh/passport-authentication-using-nodejs-express-and-mongodb-4b6a

So perhaps this'd be useful! Though @bluquar I remember you finding the Mongoose docs to be low quality, right?

**Comment by lowellbander** [comment]
This is a longer tutorial, but uses the same `passport-local-mongoose` module: https://www.sitepoint.com/local-authentication-using-passport-node-js/

**Comment by lowellbander** [comment]
I think Mongoose is worth a shot, "I figure" that if we want to go under the hood an do something custom we can still use the stock driver if we want, right? Some folks on the webernet say that Mongoose is helpful because it allows you to schematize MongoDB, but as noted in the excerpt below, the rigidity of a schema sacrifices a large benefit of MongoDB 

https://www.mongodb.com/developer/article/mongoose-versus-nodejs-driver/

> Both Mongoose and the MongoDB Node.js driver support similar functionality. While Mongoose does make MongoDB development familiar to someone who may be completely new, it does perform a lot of magic under the hood that could have unintended consequences in the future.
> 
> I personally believe that you don't need an ODM to be successful with MongoDB. I am also not a huge fan of ORMs in the relational database world. While they make initial dive into a technology feel familiar, they abstract away a lot of the power of a database.
> 
> Developers have a lot of choices to make when it comes to building applications. In this article, we looked at the differences between using an ODM versus the native driver and showed that the difference between the two is not that big. Using an ODM like Mongoose can make development feel familiar but forces you into a rigid design, which is an anti-pattern when considering building with MongoDB.
> 
> The MongoDB Node.js driver works natively with your MongoDB database to give you the best and most flexible development experience. It allows the database to do what it's best at while allowing your application to focus on what it's best at, and that's probably not managing data models.

**Comment by bluquar** [comment]
From what I've seen so far I think it makes sense to go with MongoDB directly and not use Mongoose.

**Comment by bluquar** [comment]
Although if it's easy to use both side by side, then using mongoose for user auth and not using it for other stuff sounds convenient

**Comment by lowellbander** [comment]
Okie! Next chance I get I'll try and go through [this tutorial](https://dev.to/muhammadawaisshaikh/passport-authentication-using-nodejs-express-and-mongodb-4b6a) to set up Passport with Mongoose, and then we can try implementing other stuff without Mongoose and see what happens.

OR we can go straight to using Passport without Mongoose, I'll think on it

**Comment by lowellbander** [comment]
OR I'll just go through this tutorial and try doing the mongoose-passport work myself:

**Comment by bluquar** [comment]
Yee I fuckin dare you

**Comment by lowellbander** [comment]
#26
