### ISSUE TITLE
frontend, behavioral analytics

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#38]

**Comment by lowellbander** [comment]
[Segment](https://segment.com/) looks like a very attractive option, because you can write once to log to several different analytics services (google analytics, amplitude, etc.)

**Comment by bluquar** [comment]
Node:
https://segment.com/docs/connections/sources/catalog/libraries/server/node/

Browser:
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/

React Native:
https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/

TBD: will the RN SDK work on web?

**Comment by lowellbander** [comment]
https://www.freshpaint.io/

**Comment by lowellbander** [comment]
This is a hard decision to make now, but we could choose to only support
native mobile, which would simplify development a bit (maybe a lot? Idk)

**Comment by lowellbander** [comment]
- create request
- complete request
- open app

**Comment by bluquar** [comment]
My current thinking is we should only send analytics events from the backend for now. Since we'd be able to ensure we're not missing any tracking events. The downside is if we wanted device info we'd have to log that manually.
