### ISSUE TITLE
(android) screens go blank after switching between tabs 

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#49]
![Screenshot_20211217-075445.png](https://user-images.githubusercontent.com/3479724/146572018-a66cf59a-908b-40ea-9c77-bfc91624d3aa.png)

![Screenshot_20211217-075447.png](https://user-images.githubusercontent.com/3479724/146572026-2d2c5adb-4fd8-4461-b7fa-e6f62e794876.png)

**Comment by bluquar** [comment]
Weird

**Comment by bluquar** [comment]
Fixed
