### ISSUE TITLE
Unable to create account on android app 

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#62]
Thus is using the latest build from #58

https://expo.dev/accounts/dandelion-aid-app/projects/boilerplate-expo-project/builds/a02a171b-a0ae-4a46-9e09-19ad79918f75

![Screenshot_20211219-083234.png](https://user-images.githubusercontent.com/3479724/146682831-99dab344-f08f-4a29-906b-83082374f2a5.png)

**Comment by bluquar** [comment]
Ack

**Comment by bluquar** [comment]
Fixed
