### ISSUE TITLE
"Unexpected token < in JSON at position 0" when trying to sign up in development

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#72]
And I also see no requests, idk what's happening, maybe missing environment variable? idk

![Screen Shot 2021-12-22 at 10 02 07 PM](https://user-images.githubusercontent.com/3479724/147195714-e839ad67-4240-450d-9c37-8baa45890999.png)
![Screen Shot 2021-12-22 at 10 04 08 PM](https://user-images.githubusercontent.com/3479724/147195787-dff2dbcd-2f53-435b-a5b0-ba62d70c20d6.png)

**Comment by lowellbander** [comment]
perhaps this https://stackoverflow.com/a/53209939

**Comment by lowellbander** [comment]
oh actually I looked at the network inspector and saw `Cannot POST /graphql` which led me to https://stackoverflow.com/questions/53036387/cannot-post-graphql which I think is because the `GRAPHQL_URI` environment variable isn't set at https://github.com/dandelion-community/aid-app-monorepo/settings/secrets/actions/ 

I think this is the workaround @bluquar has going so that the graphql requests are made to the "backend" server (port?), not the one serving the frontend

**Comment by lowellbander** [comment]
Tried running "backend" server separately, I think the `SEGMENT_ANALYTICS_WRITE_KEY` needs to be a repo secret, not just "environment" secret

```
@lowellbander ➜ /workspaces/aid-app-monorepo (bold-recipient-name ✗) $ npm start

> community-aid-app@0.1.0 start
> node server-build/root/runserver.js

node:assert:400
    throw err;
    ^

AssertionError [ERR_ASSERTION]: You must pass your Segment project's write key.
    at new Analytics (/workspaces/aid-app-monorepo/node_modules/analytics-node/index.js:37:5)
    at Object.<anonymous> (/workspaces/aid-app-monorepo/server-build/analytics/index.js:9:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/workspaces/aid-app-monorepo/server-build/models/User.js:44:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

**Comment by lowellbander** [comment]
@bluquar will you please add me to the Segment Workspace(?) so that I can grab our write key and try to add it as a codespace secret so that I can unblock local development?

**Comment by bluquar** [comment]
@lowellbander I couldn't figure out how to do that in the minute or so I spent trying to figure it out on the Segment website, but I just sent you my .env file on Signal as a stopgap

**Comment by lowellbander** [comment]
OK tite ty!

**Comment by lowellbander** [comment]
added `SEGMENT_ANALYTICS_WRITE_KEY` to https://github.com/dandelion-community/aid-app-monorepo/settings/secrets/codespaces, will see if codespace picks it up then try the others

**Comment by lowellbander** [comment]
added `SEGMENT_ANALYTICS_WRITE_KEY` to https://github.com/dandelion-community/aid-app-monorepo/settings/secrets/codespaces, will see if codespace picks it up then try the others

**Comment by lowellbander** [comment]
@bluquar I think I need Segment access to instrument new events by repeating that subscriber/mapping flow you did for Create Account

**Comment by lowellbander** [comment]
ugh this is frustrating, I haven't gotten `GRAPHQL_URI` into `process.env` either via the command line or with a `.env` file, idk wat to do >.>

**Comment by lowellbander** [comment]
figure i can stopgap by just hardcoding the grapql uri for now, figure out env stuff later

**Comment by lowellbander** [comment]
So my understanding is `npm start` runs the backend server, whereas `npm run web` starts expo, which serves the client? why wouldn't it be the same server? Oh is it the same, but different ports? Why different ports? Why does "backend" port 3000 serve a web ui that has my stale changes? 

When I run `npm run web` it spawns a new tab with this JSON blob in it, why?

```
{"name":"boilerplate-expo-project","slug":"boilerplate-expo-project","version":"1.0.0","orientation":"portrait","icon":"./assets/images/icon.png","scheme":"myapp","userInterfaceStyle":"automatic","splash":{"image":"./assets/images/splash.png","resizeMode":"contain","backgroundColor":"#ffffff","imageUrl":"http://127.0.0.1:19000/assets/./assets/images/splash.png"},"updates":{"fallbackToCacheTimeout":0},"assetBundlePatterns":["**/*"],"ios":{"supportsTablet":true,"bundleIdentifier":"com.dandelion-aid-app.dandelion"},"android":{"adaptiveIcon":{"foregroundImage":"./assets/images/adaptive-icon.png","backgroundColor":"#ffffff","foregroundImageUrl":"http://127.0.0.1:19000/assets/./assets/images/adaptive-icon.png"},"package":"com.dandelion_aid_app.dandelion"},"web":{"favicon":"./assets/images/favicon.png"},"_internal":{"isDebug":false,"projectRoot":"/workspaces/aid-app-monorepo","dynamicConfigPath":null,"staticConfigPath":"/workspaces/aid-app-monorepo/app.json","packageJsonPath":"/workspaces/aid-app-monorepo/package.json"},"sdkVersion":"43.0.0","platforms":["ios","android","web"],"developer":{"tool":"expo-cli","projectRoot":"/workspaces/aid-app-monorepo"},"packagerOpts":{"scheme":"exp+boilerplate-expo-project","hostType":"lan","lanType":"ip","devClient":false,"dev":true,"minify":false,"urlRandomness":null,"https":false},"mainModuleName":"node_modules/expo/AppEntry","__flipperHack":"React Native packager is running","debuggerHost":"127.0.0.1:19000","logUrl":"http://127.0.0.1:19000/logs","hostUri":"127.0.0.1:19000","bundleUrl":"http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false","iconUrl":"http://127.0.0.1:19000/assets/./assets/images/icon.png","id":"@anonymous/boilerplate-expo-project-7120d6e4-9d3a-4e4d-9c6e-87c28950266c"}

**Comment by lowellbander** [comment]
as a workaround, made `npm start` serve up to date code by rebuilding client with `npm run build:client`

**Comment by bluquar** [comment]
You can run `npm run dev:client`. That's what that run command is intended for.

You should not modify the `npm start` command in "prod" because that's what the AWS deployment runs to start the server. On AWS, the client code will have already been built.

You're right that `npm start` runs the server. The server serves both the client build and the GraphQL server.

I don't know why `npm run web` spawns a tab with that JSON blob in it for you.

**Comment by bluquar** [comment]
This development flow should work:

1. `npm run dev:server` in one shell
2. `npm run dev:client` in another shell
3. visit `localhost:3000`
