### ISSUE TITLE
optionally hide completed requests

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#77]

**Comment by lowellbander** [comment]
server already supports this!

![image](https://user-images.githubusercontent.com/3479724/147306166-3eca1352-fa82-43dc-8904-33bffc8e4f45.png)

I don't know what I need to do for the client's graphql types to reflect this :/

![image](https://user-images.githubusercontent.com/3479724/147306305-9fe57923-0365-4dce-95f7-80ac6e3f87de.png)

**Comment by bluquar** [comment]
Cool! Commented on your PR :)
