### ISSUE TITLE
`npm run dev:web` and `npm start` fail on fresh codespace

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#9]
this is fixed by `yarn install`, so perhaps this needs to be added to something in .devcontainer?

**Comment by lowellbander** [comment]
@bluquar  do you know where this would be added? I don't see anywhere in the repo where even `npm install` is explicitly run

My guess would be the `Dockerfile` but there's so many configs here that I'm not sure

**Comment by lowellbander** [comment]
`npm start` also fails on fresh codespace

**Comment by bluquar** [comment]
I don't. The current Dockerfile is very opaque. You might be able to just add "RUN yarn install" but idk
